## 为什么要学习pandas
因为pandas含有使数据分析工作变得更快和更简单的高级数据结构和操作工具  
pandas是基于numpy构建的，让以numpy为中心的应用变得更加简单

In [4]:
import pandas as pd
from pandas import Series, DataFrame

## Series类型
是一种类似于一维数组的对象，是由一组数据以及一组与之相关的数组标签组成（索引）。仅由一组数据即可产生最简单的series

In [6]:
obj = Series([1,2,3,4,5])
print(obj)
print(obj.values)
print(obj.index)

0    1
1    2
2    3
3    4
4    5
dtype: int64
[1 2 3 4 5]
RangeIndex(start=0, stop=5, step=1)

In [8]:
# 自定义索引
obj = Series(['a','b','c','d','e'], index=[1,2,3,4,5])
print(obj)
print(obj[2])

1    a
2    b
3    c
4    d
5    e
dtype: object
b

In [10]:
# 可以把series当成字典使用
data = {'a':10000, 'b':20000, 'c':30000}
obj = Series(data)  # 这个时候，series中的索引就是字典中的键
print(obj)
keys = ['a','c']
obj_1 = Series(data, index=keys)
print(obj_1)

a    10000
b    20000
c    30000
dtype: int64
a    10000
c    30000
dtype: int64

In [15]:
# 缺失数据的处理
data = {'a':None, 'b':20000, 'c':30000}
obj = Series(data)
print(obj)
pd.isnull(obj)
pd.notnull(obj)
obj.isnull()
obj.notnull()

a        NaN
b    20000.0
c    30000.0
dtype: float64

a    False
b     True
c     True
dtype: bool

In [16]:
data = {'LiLei':None, 'HanMeiMei':25, 'Tony':None, 'Jack':50}
obj = Series(data)
obj.name = 'AameAndAge'
obj.index.name = 'xingming'
print(obj)

xingming
LiLei         NaN
HanMeiMei    25.0
Tony          NaN
Jack         50.0
Name: AameAndAge, dtype: float64

## DataFrame
是一个表格型的数据结构，含有一组有序的列，每列可以是不同值的类型/数值/字符串/布尔值都可以  
本身有行索引，也有列索引  
也可以理解成是由Series组成的一个字典
DataFrame构造函数能够接收的数据类型有：
1. 二维numpy array
2. 由数组/列表或者是元组组成的字典
3. 由series组成的字典
4. 由字典组成的字典
5. 字典或series的列表
6. 由列表或者元组组成的列表
7. 另一个dataFrame

In [18]:
# 构建dataFrame
data = {
    '60年代':['狗子','嘎子','秀儿'],
    '70年代':['卫国','建国','爱国'],
    '80年代':['李雷','韩梅梅','张伟']
}
frame_data = DataFrame(data)
print(frame_data)
print(frame_data['70年代'])

  60年代 70年代 80年代
0   狗子   卫国   李雷
1   嘎子   建国  韩梅梅
2   秀儿   爱国   张伟
0    卫国
1    建国
2    爱国
Name: 70年代, dtype: object

In [21]:
import numpy as np
dates = pd.date_range('20190301', periods=6)
print(dates)

DatetimeIndex(['2019-03-01', '2019-03-02', '2019-03-03', '2019-03-04',
               '2019-03-05', '2019-03-06'],
              dtype='datetime64[ns]', freq='D')

In [30]:
df = pd.DataFrame(np.random.rand(6,4), index = dates, columns = list('ABCD'))
print(df)
print(df.T)
print(df['20190301':'20190303'])
# 对行和列同时进行筛选
print(df.loc['20190301':'20190303', ['A','B']])
print(df.at[dates[0],'A'])
# 只想看前两行
print(df.head(2))
# 只想看后两行
print(df.tail(3))

                   A         B         C         D
2019-03-01  0.622106  0.671956  0.357904  0.814228
2019-03-02  0.176721  0.314215  0.220627  0.948234
2019-03-03  0.211340  0.189167  0.094962  0.230509
2019-03-04  0.834654  0.634427  0.707434  0.753327
2019-03-05  0.187580  0.324607  0.334390  0.397123
2019-03-06  0.476227  0.120703  0.944912  0.561053
   2019-03-01  2019-03-02  2019-03-03  2019-03-04  2019-03-05  2019-03-06
A    0.622106    0.176721    0.211340    0.834654    0.187580    0.476227
B    0.671956    0.314215    0.189167    0.634427    0.324607    0.120703
C    0.357904    0.220627    0.094962    0.707434    0.334390    0.944912
D    0.814228    0.948234    0.230509    0.753327    0.397123    0.561053
                   A         B         C         D
2019-03-01  0.622106  0.671956  0.357904  0.814228
2019-03-02  0.176721  0.314215  0.220627  0.948234
2019-03-03  0.211340  0.189167  0.094962  0.230509
                   A         B
2019-03-01  0.622106  0.671956
2019-03-02  0.176721  0.314215
2019-03-03  0.211340  0.189167
0.6221059276335102
                   A         B         C         D
2019-03-01  0.622106  0.671956  0.357904  0.814228
2019-03-02  0.176721  0.314215  0.220627  0.948234
                   A         B         C         D
2019-03-04  0.834654  0.634427  0.707434  0.753327
2019-03-05  0.187580  0.324607  0.334390  0.397123
2019-03-06  0.476227  0.120703  0.944912  0.561053

## pandas重新索引

In [34]:
obj = Series([4.5, 9.8, -1.2], index=['a', 'b', 'c'])
print(obj)
# 没有数值的索引项引用none值
job_1 = obj.reindex(['a', 'b', 'c', 'd', 'e', 'f'])
print(job_1)
# 为空值填充默认值
job_2 = obj.reindex(['a', 'b', 'c', 'd', 'e', 'f'], fill_value=1)
print(job_2)

a    4.5
b    9.8
c   -1.2
dtype: float64
a    4.5
b    9.8
c   -1.2
d    NaN
e    NaN
f    NaN
dtype: float64
a    4.5
b    9.8
c   -1.2
d    1.0
e    1.0
f    1.0
dtype: float64

In [37]:
obj = Series([4.5, 9.8, -1.2], index=[0, 2, 4])
# ffill，前项值填充
o = obj.reindex(range(6), method='ffill')
print(obj)
print(o)

0    4.5
2    9.8
4   -1.2
dtype: float64
0    4.5
1    4.5
2    9.8
3    9.8
4   -1.2
5   -1.2
dtype: float64

## 算术运算和数据对齐
pandas的一个重要功能，可以对不同索引的对象进行算术运算，在将对象相加时，如果存在不同的索引对，则结果的索引就是该索引的并集

In [38]:
d1 = Series([1.3, 1.5, 2.6, -3.5], index=['a', 'b', 'c', 'd'])
d2 = Series([-1.3, -1.5, -2.6, 3.9, 9.8], index=['a', 'b', 'c', 'd', 'e'])
print(d1 + d2)

a    0.0
b    0.0
c    0.0
d    0.4
e    NaN
dtype: float64

In [39]:
df1 = DataFrame(np.arange(9).reshape((3,3)), columns=list('abc'), index=[1,2,3])
print(df1)

   a  b  c
1  0  1  2
2  3  4  5
3  6  7  8

In [41]:
df2 = DataFrame(np.arange(12).reshape((4,3)), columns=list('cde'), index=[1,2,3,4])
print(df2)

   c   d   e
1  0   1   2
2  3   4   5
3  6   7   8
4  9  10  11

In [42]:
df1 + df2

    a   b     c   d   e
1 NaN NaN   2.0 NaN NaN
2 NaN NaN   8.0 NaN NaN
3 NaN NaN  14.0 NaN NaN
4 NaN NaN   NaN NaN NaN

In [43]:
df1.add(df2, fill_value=0)  # 用0填充不重叠的值，如果本身位置为空，那么还是空

     a    b     c     d     e
1  0.0  1.0   2.0   1.0   2.0
2  3.0  4.0   8.0   4.0   5.0
3  6.0  7.0  14.0   7.0   8.0
4  NaN  NaN   9.0  10.0  11.0

## DataFrame和Series之间的运算

In [50]:
frame = DataFrame(np.arange(12).reshape(4, 3), columns = list('bde'), index = [1,2,3,4])
series = frame.loc[1]  # 选取frame中索引为1的一行数据
print(frame)
print(series)

   b   d   e
1  0   1   2
2  3   4   5
3  6   7   8
4  9  10  11
b    0
d    1
e    2
Name: 1, dtype: int32

In [46]:
# 一直向下广播相减
frame - series

   b  d  e
1  0  0  0
2  3  3  3
3  6  6  6
4  9  9  9

In [52]:
series = Series(range(3), index=list('bef'))
frame + series  # 相加时，没有就合并

     b   d     e   f
1  0.0 NaN   3.0 NaN
2  3.0 NaN   6.0 NaN
3  6.0 NaN   9.0 NaN
4  9.0 NaN  12.0 NaN

## 排序
根据条件对数据集进行排序

In [53]:
obj = Series(range(4), index = ['d', 'e', 'a', 'b'])
obj.sort_index()

a    2
b    3
d    0
e    1
dtype: int64

In [54]:
obj.sort_values()

d    0
e    1
a    2
b    3
dtype: int64

针对DataFrame，根据任意一个轴上的索引进行排序

In [55]:
frame = DataFrame(np.arange(8).reshape((2,4)), index = ['two', 'one'], columns = ['c','d','a','b'])
print(frame)

     c  d  a  b
two  0  1  2  3
one  4  5  6  7

In [56]:
frame.sort_index()

     c  d  a  b
one  4  5  6  7
two  0  1  2  3

In [57]:
# 指定轴进行排序，1表示横向轴
frame.sort_index(axis = 1)

     a  b  c  d
two  2  3  0  1
one  6  7  4  5

In [58]:
frame = DataFrame({'b':[4,7,2,-1], 'a':[0,4,2,0]})
print(frame)

   b  a
0  4  0
1  7  4
2  2  2
3 -1  0

In [60]:
frame.sort_values(by='b')

   b  a
3 -1  0
2  2  2
0  4  0
1  7  4

## 层次化索引
能够在一个轴上拥有多个索引级别。或者说，它能以低纬度形式处理高纬度数据

In [61]:
data = Series(np.random.randn(10), index = [['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'], [1,2,3,4,5,6,7,8,1,2]])
print(data)

a  1   -2.349661
   2   -0.724051
   3   -1.401259
b  4    0.349729
   5   -0.315560
   6    2.179072
c  7    0.832413
   8    2.159627
d  1    0.711811
   2   -0.794821
dtype: float64

In [62]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 4),
            ('b', 5),
            ('b', 6),
            ('c', 7),
            ('c', 8),
            ('d', 1),
            ('d', 2)],
           )

In [63]:
# 选取子集的操作
data['b']

4    0.349729
5   -0.315560
6    2.179072
dtype: float64

In [64]:
data['b':'c']

b  4    0.349729
   5   -0.315560
   6    2.179072
c  7    0.832413
   8    2.159627
dtype: float64

In [65]:
# 内层索引选取

# 第一层索引选取所有元素，第二层索引选取索引为2的元素
data[:,2]

a   -0.724051
d   -0.794821
dtype: float64

In [68]:
# 使用unstack生成新的DataFrame
data.unstack()

,1,2,3,4,5,6,7,8
a,-2.349661,-0.724051,-1.401259,NaN,NaN,NaN,NaN,NaN
b,NaN,NaN,NaN,0.349729,-0.31556,2.179072,NaN,NaN
c,NaN,NaN,NaN,NaN,NaN,NaN,0.832413,2.159627
d,0.711811,-0.794821,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
data.unstack().stack()

a  1   -2.349661
   2   -0.724051
   3   -1.401259
b  4    0.349729
   5   -0.315560
   6    2.179072
c  7    0.832413
   8    2.159627
d  1    0.711811
   2   -0.794821
dtype: float64

In [71]:
# 对于dataFrame，每条轴都可以有分层索引，各层都可以有名字
frame_data = DataFrame(np.arange(12).reshape((4,3)), index=[['a','a','b','b'],[1,2,1,2]], columns=[['Black','Yellow', 'Blue'], ['Green', 'Red', 'Green']])
print(frame_data)

    Black Yellow  Blue
    Green    Red Green
a 1     0      1     2
  2     3      4     5
b 1     6      7     8
  2     9     10    11

In [74]:
frame_data.index.names = ['key1','key2']
frame_data.columns.names = ['color1', 'color2']
frame_data

color1    Black Yellow  Blue
color2    Green    Red Green
key1 key2
a    1        0      1     2
     2        3      4     5
b    1        6      7     8
     2        9     10    11

In [84]:
frame_data = DataFrame(np.arange(12).reshape((4,3)), index=[['a','a','b','b'],[1,2,1,2]], columns=[['Black','Yellow', 'Black'], ['Green', 'Red', 'Blue']])
frame_data.index.names = ['key1','key2']
frame_data.columns.names = ['color1', 'color2']
frame_data

color1    Black Yellow Black
color2    Green    Red  Blue
key1 key2
a    1        0      1     2
     2        3      4     5
b    1        6      7     8
     2        9     10    11

In [85]:
# DataFrame层次化索引的访问
# 对列进行筛选
frame_data['Black']

color2     Green  Blue
key1 key2
a    1         0     2
     2         3     5
b    1         6     8
     2         9    11

In [86]:
# 对行和列同时进行筛选
frame_data.loc['a', ['Black']]

color1 Black
color2 Green Blue
key2
1          0    2
2          3    5

In [87]:
# 根据级别汇总统计
frame_data.sum(level='key2')

<ipython-input-87-e67d98b10ed2>:2: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  frame_data.sum(level='key2')

color1 Black Yellow Black
color2 Green    Red  Blue
key2
1          6      8    10
2         12     14    16

In [89]:
frame_data.sum(level='color2', axis=1)

<ipython-input-89-17aef9b3f7eb>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  frame_data.sum(level='color2', axis=1)

color2     Green  Red  Blue
key1 key2
a    1         0    1     2
     2         3    4     5
b    1         6    7     8
     2         9   10    11

## pandas文本格式的处理
read_csv：从文件/url/文件型对象中加载带分隔符的数据，默认分隔符为逗号  
read_table: 从文件/url/文件型对象中加载带分隔符的数据，默认分隔符为制表符\t  
read_fwf: 读取固定宽列格式数据  
read_clipboard: 读取剪切板中的数据，可以看做寿是read_table的剪切板，可以用在将网页中的数据转换为表格中数据时

In [ ]:
pd.read_csv('data1.csv')
pd.read_csv('data1.csv', header=None)  # 没有头部，所有文件里的数据都是目标数据 ，它会自动给你生成头
# 指定索引，指定c列为索引列
pd.read_csv('data1.csv', index_col='c')
# 指定多列为层次化索引
pd.read_csv('data1.csv', index_col=['c', 'd'])
# 文件中的NA代表的就是None
# 不读取哪一行
pd.read_csv('data1.csv', skiprows=[1])
# 大文件读取，只读5行
pdf.read_csv('data1.csv', nrows=5)
# 写入文件
data.to_csv('data2.csv', sep='|')
pd.read_table('data1.csv', sep=',')

## pandas 读取excel文件并画图

In [ ]:
excel = pd.read_excel('data.xlsx')
# 读取指定表
excel = pd.read_excel('data.xlsx', sheet_name='工作表2')
# 画图,散点图
pl = excel.plot(kind='scatter', x='age', y='place').get_figure()
# 保存成图片
p1.savefig('1.png')